theme: jekyll-theme-minimal
title: Leadership Tools
description: If you are looking for tools and references to help kickstart your leadership career as a game developer. You've come to the right place.
logo: img/logos/curious_cat_relax.JPG
favicon: 'favicon.png'
show_downloads: false

author: Fábio Reis